# Generated by Django 2.2.25 on 2022-01-10 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.CharField(default='22-12-2022', max_length=12)),
                ('profile_pic', models.ImageField(default='spotify.png', upload_to='')),
                ('cover_pic', models.ImageField(default='wallpaperflare.com_wallpaper.jpg', upload_to='')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=50, null=True)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_post', models.TextField(max_length=500)),
                ('img', models.ImageField(blank=True, upload_to='images')),
                ('date_published', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
