# Generated by Django 2.2.25 on 2022-01-13 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_userprofile_followeres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followeres',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followere',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
