# Generated by Django 2.2.25 on 2022-01-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220113_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followere',
        ),
    ]
