# Generated by Django 2.2.25 on 2022-01-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='retweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserPost'),
        ),
    ]
