# Generated by Django 2.2.25 on 2022-01-08 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220108_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='date_published',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpost',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
