# Generated by Django 2.2.25 on 2022-01-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220113_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='check_retweet',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
