# Generated by Django 2.2.25 on 2022-01-08 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220108_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
