# Generated by Django 2.2.25 on 2022-01-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userpost_retweet_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='retweet_user_id',
            field=models.CharField(blank=True, default=19, max_length=50),
        ),
    ]
