# Generated by Django 2.2.25 on 2022-01-14 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20220114_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetweetTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
