# Generated by Django 2.2.25 on 2022-01-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220114_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follow_check',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
