# Generated by Django 2.2.25 on 2022-01-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220115_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='check_like',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
